import type { Metadata } from 'next';
import '@/styles/style.scss';

export const metadata: Metadata = {
    title: 'KHY react guide',
    description: 'Generated by create next app',
};

export default function RootLayout({
    children,
}: Readonly<{
    children: React.ReactNode;
}>) {
    return (
        <html lang="ko">
            <body>{children}</body>
        </html>
    );
}
